const HTTP_OK_STATUS = 200;
const HTTP_CREATED_STATUS = 201;
const HTTP_BAD_REQUEST = 400;
const HTTP_NOT_FOUND_STATUS = 404;
const HTTP_UNPROCESSABLE_ENTITY = 422;
const HTTP_SERVER_ERROR = 500;

module.exports = {
  HTTP_OK_STATUS,
  HTTP_CREATED_STATUS,
  HTTP_BAD_REQUEST,
  HTTP_NOT_FOUND_STATUS,
  HTTP_UNPROCESSABLE_ENTITY,
  HTTP_SERVER_ERROR,
};
