const HTTP_OK_STATUS = 201;
const HTTP_UNPROCESSABLE_ENTITY = 422;
const HTTP_NOT_FOUND = 404;
const HTTP_CREATED = 201;

module.exports = {
  HTTP_NOT_FOUND,
  HTTP_OK_STATUS,
  HTTP_UNPROCESSABLE_ENTITY,
  HTTP_CREATED,
};