const HTTP_OK_STATUS = 200;
const HTTP_CREATE_STATUS = 201;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const HTTP_NOT_FOUND = 404;
const UNPROCESSABLE_ENTITY = 422;

module.exports = {
  HTTP_OK_STATUS,
  HTTP_CREATE_STATUS,
  BAD_REQUEST,
  UNAUTHORIZED,
  HTTP_NOT_FOUND,
  UNPROCESSABLE_ENTITY,
};
