const HTTP_OK_STATUS = 200;
const HTTP_CREATED_STATUS = 201;
// const HTTP_NOT_FOUND_STATUS = 404;
const HTTP_NO_BODY_STATUS = 422;

module.exports = {
    HTTP_OK_STATUS,
    HTTP_CREATED_STATUS,
    HTTP_NO_BODY_STATUS,
};
