const HTTP_OK_STATUS = 200;
const HTTP_UNPROCESSABLE_ENTITY = 422;
const HTTP_CREATED = 201;
const HTTP_INTERNAL_SERVER_ERROR = 500;
const HTTP_NOT_FOUND = 404;

module.exports = {
  HTTP_OK_STATUS,
  HTTP_UNPROCESSABLE_ENTITY,
  HTTP_CREATED,
  HTTP_INTERNAL_SERVER_ERROR,
  HTTP_NOT_FOUND,
};